export const PROBLEM_LIST_REQUEST = "PROBLEM_LIST_REQUEST";
export const PROBLEM_LIST_SUCCESS = "PROBLEM_LIST_SUCCESS";
export const PROBLEM_LIST_FAIL = "PROBLEM_LIST_FAIL";

export const PROBLEM_DETAILS_REQUEST = "PROBLEM_DETAILS_REQUEST";
export const PROBLEM_DETAILS_SUCCESS = "PROBLEM_DETAILS_SUCCESS";
export const PROBLEM_DETAILS_FAIL = "PROBLEM_DETAILS_FAIL";

export const PROBLEM_DELETE_REQUEST = "PROBLEM_DELETE_REQUEST";
export const PROBLEM_DELETE_SUCCESS = "PROBLEM_DELETE_SUCCESS";
export const PROBLEM_DELETE_FAIL = "PROBLEM_DELETE_FAIL";

export const PROBLEM_CREATE_REQUEST = "PROBLEM_CREATE_REQUEST";
export const PROBLEM_CREATE_SUCCESS = "PROBLEM_CREATE_SUCCESS";
export const PROBLEM_CREATE_FAIL = "PROBLEM_CREATE_FAIL";
export const PROBLEM_CREATE_RESET = "PROBLEM_CREATE_RESET";

export const PROBLEM_UPDATE_REQUEST = "PROBLEM_UPDATE_REQUEST";
export const PROBLEM_UPDATE_SUCCESS = "PROBLEM_UPDATE_SUCCESS";
export const PROBLEM_UPDATE_FAIL = "PROBLEM_UPDATE_FAIL";
export const PROBLEM_UPDATE_RESET = "PROBLEM_UPDATE_RESET";
