export const PROBLEM_LIST_REQUEST = "PROBLEM_LIST_REQUEST";
export const PROBLEM_LIST_SUCCESS = "PROBLEM_LIST_SUCCESS";
export const PROBLEM_LIST_FAIL = "PROBLEM_LIST_FAIL";

export const PROBLEM_DETAILS_REQUEST = "PROBLEM_DETAILS_REQUEST";
export const PROBLEM_DETAILS_SUCCESS = "PROBLEM_DETAILS_SUCCESS";
export const PROBLEM_DETAILS_FAIL = "PROBLEM_DETAILS_FAIL";
